// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;

import 'dart:typed_data' as i2;

import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    franchises,
    rooms,
    meals,
    gigs,
    viewings,
    games,
  ];
  late final Shape0 franchises = Shape0(
    source: i0.VersionedTable(
      entityName: 'franchises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 rooms = Shape1(
    source: i0.VersionedTable(
      entityName: 'rooms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 meals = Shape2(
    source: i0.VersionedTable(
      entityName: 'meals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 gigs = Shape3(
    source: i0.VersionedTable(
      entityName: 'gigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_14,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 viewings = Shape4(
    source: i0.VersionedTable(
      entityName: 'viewings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 games = Shape5(
    source: i0.VersionedTable(
      entityName: 'games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_26,
        _column_27,
        _column_28,
        _column_22,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get logoPath =>
      columnsByName['logo_path']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'logo_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get photoPath =>
      columnsByName['photo_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get franchiseId =>
      columnsByName['franchise_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get escaped =>
      columnsByName['escaped']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get timeLeftMinutes =>
      columnsByName['time_left_minutes']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'photo_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_6(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'rating',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'review',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'happened_on',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'franchise_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES franchises(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'escaped',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (escaped IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'time_left_minutes',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get photoPath =>
      columnsByName['photo_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get dish =>
      columnsByName['dish']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get price =>
      columnsByName['price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get company =>
      columnsByName['company']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dish',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_13(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'price',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'company',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'location',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get photoPath =>
      columnsByName['photo_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get venue =>
      columnsByName['venue']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get city =>
      columnsByName['city']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get supportActs =>
      columnsByName['support_acts']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get setlist =>
      columnsByName['setlist']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get company =>
      columnsByName['company']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'venue',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'city',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'support_acts',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'setlist',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'external_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get photoPath =>
      columnsByName['photo_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get releaseYear =>
      columnsByName['release_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get director =>
      columnsByName['director']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cast =>
      columnsByName['cast']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get season =>
      columnsByName['season']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'release_year',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'director',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cast',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'season',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get photoPath =>
      columnsByName['photo_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get status =>
      columnsByName['status']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get platform =>
      columnsByName['platform']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get hoursPlayed =>
      columnsByName['hours_played']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get releaseYear =>
      columnsByName['release_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'platform',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_28(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'hours_played',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    franchises,
    rooms,
    meals,
    gigs,
    viewings,
    games,
  ];
  late final Shape0 franchises = Shape0(
    source: i0.VersionedTable(
      entityName: 'franchises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 rooms = Shape6(
    source: i0.VersionedTable(
      entityName: 'rooms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 meals = Shape7(
    source: i0.VersionedTable(
      entityName: 'meals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 gigs = Shape8(
    source: i0.VersionedTable(
      entityName: 'gigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_14,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 viewings = Shape9(
    source: i0.VersionedTable(
      entityName: 'viewings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 games = Shape10(
    source: i0.VersionedTable(
      entityName: 'games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_26,
        _column_27,
        _column_28,
        _column_22,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get franchiseId =>
      columnsByName['franchise_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get escaped =>
      columnsByName['escaped']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get timeLeftMinutes =>
      columnsByName['time_left_minutes']! as i1.GeneratedColumn<int>;
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get dish =>
      columnsByName['dish']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get price =>
      columnsByName['price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get company =>
      columnsByName['company']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get venue =>
      columnsByName['venue']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get city =>
      columnsByName['city']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get supportActs =>
      columnsByName['support_acts']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get setlist =>
      columnsByName['setlist']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get company =>
      columnsByName['company']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get releaseYear =>
      columnsByName['release_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get director =>
      columnsByName['director']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cast =>
      columnsByName['cast']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get season =>
      columnsByName['season']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get status =>
      columnsByName['status']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get platform =>
      columnsByName['platform']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get hoursPlayed =>
      columnsByName['hours_played']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get releaseYear =>
      columnsByName['release_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
}

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    franchises,
    rooms,
    meals,
    gigs,
    viewings,
    games,
  ];
  late final Shape11 franchises = Shape11(
    source: i0.VersionedTable(
      entityName: 'franchises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_29, _column_1, _column_2, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 rooms = Shape12(
    source: i0.VersionedTable(
      entityName: 'rooms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_31,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 meals = Shape13(
    source: i0.VersionedTable(
      entityName: 'meals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 gigs = Shape14(
    source: i0.VersionedTable(
      entityName: 'gigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_14,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 viewings = Shape15(
    source: i0.VersionedTable(
      entityName: 'viewings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 games = Shape16(
    source: i0.VersionedTable(
      entityName: 'games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_26,
        _column_27,
        _column_28,
        _column_22,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get logoPath =>
      columnsByName['logo_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get franchiseId =>
      columnsByName['franchise_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get escaped =>
      columnsByName['escaped']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get timeLeftMinutes =>
      columnsByName['time_left_minutes']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'franchise_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES franchises(id)ON DELETE SET NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get dish =>
      columnsByName['dish']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get price =>
      columnsByName['price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get company =>
      columnsByName['company']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get venue =>
      columnsByName['venue']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get city =>
      columnsByName['city']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get supportActs =>
      columnsByName['support_acts']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get setlist =>
      columnsByName['setlist']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get company =>
      columnsByName['company']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
}

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get releaseYear =>
      columnsByName['release_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get director =>
      columnsByName['director']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cast =>
      columnsByName['cast']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get season =>
      columnsByName['season']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
}

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get status =>
      columnsByName['status']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get platform =>
      columnsByName['platform']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get hoursPlayed =>
      columnsByName['hours_played']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get releaseYear =>
      columnsByName['release_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
}

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    franchises,
    rooms,
    meals,
    gigs,
    viewings,
    games,
  ];
  late final Shape11 franchises = Shape11(
    source: i0.VersionedTable(
      entityName: 'franchises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_29, _column_1, _column_2, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 rooms = Shape12(
    source: i0.VersionedTable(
      entityName: 'rooms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_31,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 meals = Shape13(
    source: i0.VersionedTable(
      entityName: 'meals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 gigs = Shape14(
    source: i0.VersionedTable(
      entityName: 'gigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_14,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 viewings = Shape17(
    source: i0.VersionedTable(
      entityName: 'viewings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_20,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 games = Shape16(
    source: i0.VersionedTable(
      entityName: 'games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_26,
        _column_27,
        _column_28,
        _column_22,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get releaseYear =>
      columnsByName['release_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get director =>
      columnsByName['director']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cast =>
      columnsByName['cast']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get season =>
      columnsByName['season']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get posterUrl =>
      columnsByName['poster_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get backdropUrl =>
      columnsByName['backdrop_url']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'poster_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'backdrop_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    franchises,
    rooms,
    meals,
    gigs,
    viewings,
    games,
  ];
  late final Shape11 franchises = Shape11(
    source: i0.VersionedTable(
      entityName: 'franchises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_29, _column_1, _column_2, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 rooms = Shape12(
    source: i0.VersionedTable(
      entityName: 'rooms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_31,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 meals = Shape13(
    source: i0.VersionedTable(
      entityName: 'meals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 gigs = Shape14(
    source: i0.VersionedTable(
      entityName: 'gigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_14,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 viewings = Shape17(
    source: i0.VersionedTable(
      entityName: 'viewings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_20,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 games = Shape18(
    source: i0.VersionedTable(
      entityName: 'games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_26,
        _column_27,
        _column_28,
        _column_22,
        _column_20,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape18 extends i0.VersionedTable {
  Shape18({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get status =>
      columnsByName['status']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get platform =>
      columnsByName['platform']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get hoursPlayed =>
      columnsByName['hours_played']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get releaseYear =>
      columnsByName['release_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverUrl =>
      columnsByName['cover_url']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    franchises,
    rooms,
    meals,
    gigs,
    viewings,
    games,
    entryPhotos,
    photoByOwner,
  ];
  late final Shape11 franchises = Shape11(
    source: i0.VersionedTable(
      entityName: 'franchises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_29, _column_1, _column_2, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 rooms = Shape12(
    source: i0.VersionedTable(
      entityName: 'rooms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_31,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 meals = Shape13(
    source: i0.VersionedTable(
      entityName: 'meals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 gigs = Shape14(
    source: i0.VersionedTable(
      entityName: 'gigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_14,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 viewings = Shape17(
    source: i0.VersionedTable(
      entityName: 'viewings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_20,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 games = Shape18(
    source: i0.VersionedTable(
      entityName: 'games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_26,
        _column_27,
        _column_28,
        _column_22,
        _column_20,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 entryPhotos = Shape19(
    source: i0.VersionedTable(
      entityName: 'entry_photos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_29, _column_35, _column_36, _column_37, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index photoByOwner = i1.Index(
    'photo_by_owner',
    'CREATE INDEX IF NOT EXISTS photo_by_owner ON entry_photos (owner_id)',
  );
}

class Shape19 extends i0.VersionedTable {
  Shape19({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ownerId =>
      columnsByName['owner_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get bytes =>
      columnsByName['bytes']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get mimeType =>
      columnsByName['mime_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'owner_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_36(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'bytes',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mime_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema8 extends i0.VersionedSchema {
  Schema8({required super.database}) : super(version: 8);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    franchises,
    rooms,
    meals,
    gigs,
    viewings,
    games,
    entryPhotos,
    wishes,
    photoByOwner,
    wishByKind,
  ];
  late final Shape11 franchises = Shape11(
    source: i0.VersionedTable(
      entityName: 'franchises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_29, _column_1, _column_2, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 rooms = Shape12(
    source: i0.VersionedTable(
      entityName: 'rooms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_31,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 meals = Shape13(
    source: i0.VersionedTable(
      entityName: 'meals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 gigs = Shape14(
    source: i0.VersionedTable(
      entityName: 'gigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_14,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 viewings = Shape17(
    source: i0.VersionedTable(
      entityName: 'viewings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_20,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 games = Shape18(
    source: i0.VersionedTable(
      entityName: 'games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_26,
        _column_27,
        _column_28,
        _column_22,
        _column_20,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 entryPhotos = Shape19(
    source: i0.VersionedTable(
      entityName: 'entry_photos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_29, _column_35, _column_36, _column_37, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 wishes = Shape20(
    source: i0.VersionedTable(
      entityName: 'wishes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_21,
        _column_3,
        _column_38,
        _column_5,
        _column_22,
        _column_20,
        _column_32,
        _column_39,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index photoByOwner = i1.Index(
    'photo_by_owner',
    'CREATE INDEX IF NOT EXISTS photo_by_owner ON entry_photos (owner_id)',
  );
  final i1.Index wishByKind = i1.Index(
    'wish_by_kind',
    'CREATE INDEX IF NOT EXISTS wish_by_kind ON wishes (kind)',
  );
}

class Shape20 extends i0.VersionedTable {
  Shape20({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get releaseYear =>
      columnsByName['release_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get posterUrl =>
      columnsByName['poster_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get addedOn =>
      columnsByName['added_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'added_on',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema9 extends i0.VersionedSchema {
  Schema9({required super.database}) : super(version: 9);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    franchises,
    rooms,
    meals,
    gigs,
    viewings,
    games,
    entryPhotos,
    wishes,
    photoByOwner,
    wishByKind,
  ];
  late final Shape11 franchises = Shape11(
    source: i0.VersionedTable(
      entityName: 'franchises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_29, _column_1, _column_2, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 rooms = Shape12(
    source: i0.VersionedTable(
      entityName: 'rooms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_31,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 meals = Shape21(
    source: i0.VersionedTable(
      entityName: 'meals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_12,
        _column_13,
        _column_14,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 gigs = Shape14(
    source: i0.VersionedTable(
      entityName: 'gigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_14,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 viewings = Shape17(
    source: i0.VersionedTable(
      entityName: 'viewings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_20,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 games = Shape18(
    source: i0.VersionedTable(
      entityName: 'games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_26,
        _column_27,
        _column_28,
        _column_22,
        _column_20,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 entryPhotos = Shape19(
    source: i0.VersionedTable(
      entityName: 'entry_photos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_29, _column_35, _column_36, _column_37, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 wishes = Shape20(
    source: i0.VersionedTable(
      entityName: 'wishes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_21,
        _column_3,
        _column_38,
        _column_5,
        _column_22,
        _column_20,
        _column_32,
        _column_39,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index photoByOwner = i1.Index(
    'photo_by_owner',
    'CREATE INDEX IF NOT EXISTS photo_by_owner ON entry_photos (owner_id)',
  );
  final i1.Index wishByKind = i1.Index(
    'wish_by_kind',
    'CREATE INDEX IF NOT EXISTS wish_by_kind ON wishes (kind)',
  );
}

class Shape21 extends i0.VersionedTable {
  Shape21({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get dish =>
      columnsByName['dish']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get price =>
      columnsByName['price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get company =>
      columnsByName['company']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mapsUrl =>
      columnsByName['maps_url']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'maps_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema10 extends i0.VersionedSchema {
  Schema10({required super.database}) : super(version: 10);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    franchises,
    rooms,
    meals,
    gigs,
    viewings,
    games,
    entryPhotos,
    wishes,
    photoByOwner,
    wishByKind,
  ];
  late final Shape11 franchises = Shape11(
    source: i0.VersionedTable(
      entityName: 'franchises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_29, _column_1, _column_2, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 rooms = Shape12(
    source: i0.VersionedTable(
      entityName: 'rooms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_31,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 meals = Shape21(
    source: i0.VersionedTable(
      entityName: 'meals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_12,
        _column_13,
        _column_14,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape22 gigs = Shape22(
    source: i0.VersionedTable(
      entityName: 'gigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_14,
        _column_20,
        _column_41,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 viewings = Shape17(
    source: i0.VersionedTable(
      entityName: 'viewings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_20,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 games = Shape18(
    source: i0.VersionedTable(
      entityName: 'games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_26,
        _column_27,
        _column_28,
        _column_22,
        _column_20,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 entryPhotos = Shape19(
    source: i0.VersionedTable(
      entityName: 'entry_photos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_29, _column_35, _column_36, _column_37, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 wishes = Shape20(
    source: i0.VersionedTable(
      entityName: 'wishes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_21,
        _column_3,
        _column_38,
        _column_5,
        _column_22,
        _column_20,
        _column_32,
        _column_39,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index photoByOwner = i1.Index(
    'photo_by_owner',
    'CREATE INDEX IF NOT EXISTS photo_by_owner ON entry_photos (owner_id)',
  );
  final i1.Index wishByKind = i1.Index(
    'wish_by_kind',
    'CREATE INDEX IF NOT EXISTS wish_by_kind ON wishes (kind)',
  );
}

class Shape22 extends i0.VersionedTable {
  Shape22({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get venue =>
      columnsByName['venue']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get city =>
      columnsByName['city']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get supportActs =>
      columnsByName['support_acts']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get setlist =>
      columnsByName['setlist']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get company =>
      columnsByName['company']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get photosUrl =>
      columnsByName['photos_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get videoUrl =>
      columnsByName['video_url']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'photos_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'video_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema11 extends i0.VersionedSchema {
  Schema11({required super.database}) : super(version: 11);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    franchises,
    rooms,
    meals,
    gigs,
    viewings,
    games,
    books,
    entryPhotos,
    wishes,
    photoByOwner,
    wishByKind,
  ];
  late final Shape11 franchises = Shape11(
    source: i0.VersionedTable(
      entityName: 'franchises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_29, _column_1, _column_2, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 rooms = Shape12(
    source: i0.VersionedTable(
      entityName: 'rooms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_31,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 meals = Shape21(
    source: i0.VersionedTable(
      entityName: 'meals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_12,
        _column_13,
        _column_14,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape22 gigs = Shape22(
    source: i0.VersionedTable(
      entityName: 'gigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_14,
        _column_20,
        _column_41,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 viewings = Shape17(
    source: i0.VersionedTable(
      entityName: 'viewings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_20,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 games = Shape18(
    source: i0.VersionedTable(
      entityName: 'games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_26,
        _column_27,
        _column_28,
        _column_22,
        _column_20,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape23 books = Shape23(
    source: i0.VersionedTable(
      entityName: 'books',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_3,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_30,
        _column_43,
        _column_44,
        _column_20,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 entryPhotos = Shape19(
    source: i0.VersionedTable(
      entityName: 'entry_photos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_29, _column_35, _column_36, _column_37, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 wishes = Shape20(
    source: i0.VersionedTable(
      entityName: 'wishes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_29,
        _column_21,
        _column_3,
        _column_38,
        _column_5,
        _column_22,
        _column_20,
        _column_32,
        _column_39,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index photoByOwner = i1.Index(
    'photo_by_owner',
    'CREATE INDEX IF NOT EXISTS photo_by_owner ON entry_photos (owner_id)',
  );
  final i1.Index wishByKind = i1.Index(
    'wish_by_kind',
    'CREATE INDEX IF NOT EXISTS wish_by_kind ON wishes (kind)',
  );
}

class Shape23 extends i0.VersionedTable {
  Shape23({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get review =>
      columnsByName['review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get happenedOn =>
      columnsByName['happened_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get author =>
      columnsByName['author']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get publicationYear =>
      columnsByName['publication_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverUrl =>
      columnsByName['cover_url']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'author',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'publication_year',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
  required Future<void> Function(i1.Migrator m, Schema11 schema) from10To11,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      case 7:
        final schema = Schema8(database: database);
        final migrator = i1.Migrator(database, schema);
        await from7To8(migrator, schema);
        return 8;
      case 8:
        final schema = Schema9(database: database);
        final migrator = i1.Migrator(database, schema);
        await from8To9(migrator, schema);
        return 9;
      case 9:
        final schema = Schema10(database: database);
        final migrator = i1.Migrator(database, schema);
        await from9To10(migrator, schema);
        return 10;
      case 10:
        final schema = Schema11(database: database);
        final migrator = i1.Migrator(database, schema);
        await from10To11(migrator, schema);
        return 11;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
  required Future<void> Function(i1.Migrator m, Schema11 schema) from10To11,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
    from7To8: from7To8,
    from8To9: from8To9,
    from9To10: from9To10,
    from10To11: from10To11,
  ),
);
